//
//  DataService.swift
//  ThinkBiz
//
//  Created by Han Yang Chin on 24/04/17.
//  Copyright © 2017 Han Yang Chin. All rights reserved.
//

import Foundation
import UIKit
import CoreData
import Firebase

class DataService {
    
    // MARK: - Shared Instance
    
    static let sharedInstance: DataService = DataService()
    
    var viewContext: NSManagedObjectContext?
    
    // MARK: - Private
    
    // Singleton
    private init() { }
    
    // MARK: - Functions
    
    // MARK: CRUD Idea
    
    func addIdea(ideaData: Dictionary<String, Any>) -> Void {
        
        if let context = viewContext {
            
            // Create a new idea object
            let idea = Idea(context: context)
            idea.name = ideaData[IdeaKV.Name.rawValue] as? String
            idea.idea = ideaData[IdeaKV.Idea.rawValue] as? String
            idea.notes = ideaData[IdeaKV.Notes.rawValue] as? String
            idea.created = ideaData[IdeaKV.Created.rawValue] as? NSDate
            
            do {
                let refCloudIdea = ApiService.sharedInstance.REF_IDEAS.childByAutoId()
                
                // Update the uid generated by Firebase
                idea.uid = refCloudIdea.key
                
                // First make a modifyable copy
                var ideaDataCopy = ideaData
                
                // Also add the uid to data object before saving to the cloud
                ideaDataCopy[IdeaKV.UID.rawValue] = idea.uid
                
                // First convert the data to native type for cloud storage
                let cloudData = convertDataForCloud(data: ideaDataCopy)
                
                // Child updates are transactional
                if let refUserIdeas = ApiService.sharedInstance.REF_USER_IDEAS {
                    let childUpdates = ["\(refCloudIdea.key)": cloudData]
                    refUserIdeas.updateChildValues(childUpdates)
                }

                try context.save()
                print("Idea saved locally")

            } catch let error as NSError {
                print("\(error)")
            }
        }
    }
    
    func updateIdea(idea: Idea, ideaData: Dictionary<String, Any>) -> Void {

        if let context = viewContext {
            // Get updated properties from ideaData
            let updatedName = ideaData[IdeaKV.Name.rawValue] as? String ?? ""
            let updatedIdea = ideaData[IdeaKV.Idea.rawValue] as? String ?? ""
            let updatedNotes = ideaData[IdeaKV.Notes.rawValue] as? String ?? ""
            
            do {
                // Child updates are transactional
                if let refUserIdeas = ApiService.sharedInstance.REF_USER_IDEAS, let ideaUID = idea.uid {
                    let refUserIdea = refUserIdeas.child(ideaUID)
                    // When dealing with concurrency use run transaction block
                    refUserIdea.runTransactionBlock({ (currentMutableData: FIRMutableData) -> FIRTransactionResult in
                        // Get most recent idea from the cloud as dictionary
                        if var tempCloudIdea = currentMutableData.value as? [String: Any] {
                            tempCloudIdea[IdeaKV.Name.rawValue] = updatedName
                            tempCloudIdea[IdeaKV.Idea.rawValue] = updatedIdea
                            tempCloudIdea[IdeaKV.Notes.rawValue] = updatedNotes
                            
                            // Set and update mutable data dictionary with updated cloudIdea properties
                            currentMutableData.value = tempCloudIdea
                            
                            return FIRTransactionResult.success(withValue: currentMutableData)
                        }
                        return FIRTransactionResult.success(withValue: currentMutableData)
                    }, andCompletionBlock: { (error, completion, snapshot) in
                        if let error = error {
                            print(error.localizedDescription)
                        }
                    })
                }
                
                // TODO: Shift this saving core data code to observe event
                idea.name = updatedName
                idea.idea = updatedIdea
                idea.notes = updatedNotes
                
                try context.save()
                print("Updated idea")
            } catch let error as NSError {
                print("\(error)")
            }
        }

    }
    
    func deleteIdea(idea: Idea) -> Void {
        print("Deleting new idea")
        
        if let context = viewContext {
            if let refUserIdeas = ApiService.sharedInstance.REF_USER_IDEAS, let ideaUID = idea.uid {
                refUserIdeas.child(ideaUID).removeValue()
            }
            
            context.delete(idea)
            do {
                try context.save()
            } catch let error as NSError {
                print("\(error)")
            }
        }
    }
    
    // MARK: - Private functions
    
    private func convertDataForCloud(data: Dictionary<String, Any>) -> Dictionary<String, Any> {
        var tempData = data
        for key in tempData.keys {
            let item = tempData[key]
            if let date = item as? NSDate {
                let dateFormatter = DateFormatter()
                dateFormatter.dateFormat = "yyyy-MM-dd HH:mm:ss zzz"
                
                let dateString = dateFormatter.string(from: date as Date)
                tempData[key] = dateString
            }
        }
        return tempData
    }
}
